/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncSalaryUpdatesRouteImport } from './routes/syncSalaryUpdates'
import { Route as SyncDeelEmployeesRouteImport } from './routes/syncDeelEmployees'
import { Route as ScheduleCheckInsRouteImport } from './routes/scheduleCheckIns'
import { Route as SalaryDeviationCheckerRouteImport } from './routes/salaryDeviationChecker'
import { Route as SalarySyncStatusRouteImport } from './routes/salary-sync-status'
import { Route as RunScheduledJobsRouteImport } from './routes/runScheduledJobs'
import { Route as ReceiveKeeperTestResultsRouteImport } from './routes/receiveKeeperTestResults'
import { Route as ProposedHiresRouteImport } from './routes/proposed-hires'
import { Route as OrgChartRouteImport } from './routes/org-chart'
import { Route as ManagementRouteImport } from './routes/management'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeEmployeeIdRouteImport } from './routes/employee.$employeeId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SyncSalaryUpdatesRoute = SyncSalaryUpdatesRouteImport.update({
  id: '/syncSalaryUpdates',
  path: '/syncSalaryUpdates',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncDeelEmployeesRoute = SyncDeelEmployeesRouteImport.update({
  id: '/syncDeelEmployees',
  path: '/syncDeelEmployees',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleCheckInsRoute = ScheduleCheckInsRouteImport.update({
  id: '/scheduleCheckIns',
  path: '/scheduleCheckIns',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryDeviationCheckerRoute = SalaryDeviationCheckerRouteImport.update({
  id: '/salaryDeviationChecker',
  path: '/salaryDeviationChecker',
  getParentRoute: () => rootRouteImport,
} as any)
const SalarySyncStatusRoute = SalarySyncStatusRouteImport.update({
  id: '/salary-sync-status',
  path: '/salary-sync-status',
  getParentRoute: () => rootRouteImport,
} as any)
const RunScheduledJobsRoute = RunScheduledJobsRouteImport.update({
  id: '/runScheduledJobs',
  path: '/runScheduledJobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveKeeperTestResultsRoute =
  ReceiveKeeperTestResultsRouteImport.update({
    id: '/receiveKeeperTestResults',
    path: '/receiveKeeperTestResults',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProposedHiresRoute = ProposedHiresRouteImport.update({
  id: '/proposed-hires',
  path: '/proposed-hires',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgChartRoute = OrgChartRouteImport.update({
  id: '/org-chart',
  path: '/org-chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementRoute = ManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEmployeeIdRoute = EmployeeEmployeeIdRouteImport.update({
  id: '/employee/$employeeId',
  path: '/employee/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/org-chart': typeof OrgChartRoute
  '/proposed-hires': typeof ProposedHiresRoute
  '/receiveKeeperTestResults': typeof ReceiveKeeperTestResultsRoute
  '/runScheduledJobs': typeof RunScheduledJobsRoute
  '/salary-sync-status': typeof SalarySyncStatusRoute
  '/salaryDeviationChecker': typeof SalaryDeviationCheckerRoute
  '/scheduleCheckIns': typeof ScheduleCheckInsRoute
  '/syncDeelEmployees': typeof SyncDeelEmployeesRoute
  '/syncSalaryUpdates': typeof SyncSalaryUpdatesRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/org-chart': typeof OrgChartRoute
  '/proposed-hires': typeof ProposedHiresRoute
  '/receiveKeeperTestResults': typeof ReceiveKeeperTestResultsRoute
  '/runScheduledJobs': typeof RunScheduledJobsRoute
  '/salary-sync-status': typeof SalarySyncStatusRoute
  '/salaryDeviationChecker': typeof SalaryDeviationCheckerRoute
  '/scheduleCheckIns': typeof ScheduleCheckInsRoute
  '/syncDeelEmployees': typeof SyncDeelEmployeesRoute
  '/syncSalaryUpdates': typeof SyncSalaryUpdatesRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/analytics': typeof AnalyticsRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/management': typeof ManagementRoute
  '/org-chart': typeof OrgChartRoute
  '/proposed-hires': typeof ProposedHiresRoute
  '/receiveKeeperTestResults': typeof ReceiveKeeperTestResultsRoute
  '/runScheduledJobs': typeof RunScheduledJobsRoute
  '/salary-sync-status': typeof SalarySyncStatusRoute
  '/salaryDeviationChecker': typeof SalaryDeviationCheckerRoute
  '/scheduleCheckIns': typeof ScheduleCheckInsRoute
  '/syncDeelEmployees': typeof SyncDeelEmployeesRoute
  '/syncSalaryUpdates': typeof SyncSalaryUpdatesRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/analytics'
    | '/error'
    | '/login'
    | '/management'
    | '/org-chart'
    | '/proposed-hires'
    | '/receiveKeeperTestResults'
    | '/runScheduledJobs'
    | '/salary-sync-status'
    | '/salaryDeviationChecker'
    | '/scheduleCheckIns'
    | '/syncDeelEmployees'
    | '/syncSalaryUpdates'
    | '/employee/$employeeId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/analytics'
    | '/error'
    | '/login'
    | '/management'
    | '/org-chart'
    | '/proposed-hires'
    | '/receiveKeeperTestResults'
    | '/runScheduledJobs'
    | '/salary-sync-status'
    | '/salaryDeviationChecker'
    | '/scheduleCheckIns'
    | '/syncDeelEmployees'
    | '/syncSalaryUpdates'
    | '/employee/$employeeId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/analytics'
    | '/error'
    | '/login'
    | '/management'
    | '/org-chart'
    | '/proposed-hires'
    | '/receiveKeeperTestResults'
    | '/runScheduledJobs'
    | '/salary-sync-status'
    | '/salaryDeviationChecker'
    | '/scheduleCheckIns'
    | '/syncDeelEmployees'
    | '/syncSalaryUpdates'
    | '/employee/$employeeId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  ManagementRoute: typeof ManagementRoute
  OrgChartRoute: typeof OrgChartRoute
  ProposedHiresRoute: typeof ProposedHiresRoute
  ReceiveKeeperTestResultsRoute: typeof ReceiveKeeperTestResultsRoute
  RunScheduledJobsRoute: typeof RunScheduledJobsRoute
  SalarySyncStatusRoute: typeof SalarySyncStatusRoute
  SalaryDeviationCheckerRoute: typeof SalaryDeviationCheckerRoute
  ScheduleCheckInsRoute: typeof ScheduleCheckInsRoute
  SyncDeelEmployeesRoute: typeof SyncDeelEmployeesRoute
  SyncSalaryUpdatesRoute: typeof SyncSalaryUpdatesRoute
  EmployeeEmployeeIdRoute: typeof EmployeeEmployeeIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syncSalaryUpdates': {
      id: '/syncSalaryUpdates'
      path: '/syncSalaryUpdates'
      fullPath: '/syncSalaryUpdates'
      preLoaderRoute: typeof SyncSalaryUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syncDeelEmployees': {
      id: '/syncDeelEmployees'
      path: '/syncDeelEmployees'
      fullPath: '/syncDeelEmployees'
      preLoaderRoute: typeof SyncDeelEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduleCheckIns': {
      id: '/scheduleCheckIns'
      path: '/scheduleCheckIns'
      fullPath: '/scheduleCheckIns'
      preLoaderRoute: typeof ScheduleCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salaryDeviationChecker': {
      id: '/salaryDeviationChecker'
      path: '/salaryDeviationChecker'
      fullPath: '/salaryDeviationChecker'
      preLoaderRoute: typeof SalaryDeviationCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary-sync-status': {
      id: '/salary-sync-status'
      path: '/salary-sync-status'
      fullPath: '/salary-sync-status'
      preLoaderRoute: typeof SalarySyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runScheduledJobs': {
      id: '/runScheduledJobs'
      path: '/runScheduledJobs'
      fullPath: '/runScheduledJobs'
      preLoaderRoute: typeof RunScheduledJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiveKeeperTestResults': {
      id: '/receiveKeeperTestResults'
      path: '/receiveKeeperTestResults'
      fullPath: '/receiveKeeperTestResults'
      preLoaderRoute: typeof ReceiveKeeperTestResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposed-hires': {
      id: '/proposed-hires'
      path: '/proposed-hires'
      fullPath: '/proposed-hires'
      preLoaderRoute: typeof ProposedHiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-chart': {
      id: '/org-chart'
      path: '/org-chart'
      fullPath: '/org-chart'
      preLoaderRoute: typeof OrgChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management': {
      id: '/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof ManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$employeeId': {
      id: '/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof EmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  ManagementRoute: ManagementRoute,
  OrgChartRoute: OrgChartRoute,
  ProposedHiresRoute: ProposedHiresRoute,
  ReceiveKeeperTestResultsRoute: ReceiveKeeperTestResultsRoute,
  RunScheduledJobsRoute: RunScheduledJobsRoute,
  SalarySyncStatusRoute: SalarySyncStatusRoute,
  SalaryDeviationCheckerRoute: SalaryDeviationCheckerRoute,
  ScheduleCheckInsRoute: ScheduleCheckInsRoute,
  SyncDeelEmployeesRoute: SyncDeelEmployeesRoute,
  SyncSalaryUpdatesRoute: SyncSalaryUpdatesRoute,
  EmployeeEmployeeIdRoute: EmployeeEmployeeIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
